---
kind: Template
apiVersion:  template.openshift.io/v1
labels:
  app: "${NAME}"
  build: "${NAME}"
  template: "metabase-postgresql-bc"
metadata:
  name: metabase
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${NAME}"
    spec:
      lookupPolicy:
        local: false
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${NAME}"
      labels:
        buildconfig: "${NAME}"
    spec:
      completionDeadlineSeconds: 600
      failedBuildsHistoryLimit: 3
      successfulBuildsHistoryLimit: 3
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}:${VERSION}"
      postCommit: {}
      resources:
        limits:
          cpu: 2000m
          memory: 2Gi
        requests:
          cpu: 1000m
          memory: 1Gi
      runPolicy: SerialLatestOnly
      source:
        dockerfile: |
          FROM BuildConfig
          ARG TZ=America/Vancouver

          RUN groupadd --system metabase && \
              useradd --system -g metabase --no-create-home metabase &&\
              mkdir -p /opt/metabase && \
              touch /var/log/metabase.log && \
              touch /etc/default/metabase

          RUN chown -R metabase:metabase /opt/metabase && \
              chown metabase:metabase /var/log/metabase.log  && \
              chmod 640 /etc/default/metabase

          WORKDIR /opt/metabase
          ENV FC_LANG=en-US \
              LC_CTYPE=en_US.UTF-8

          RUN yum -y update
          RUN yum install -y java-11-openjdk-devel wget

          RUN wget -q https://downloads.metabase.com/latest/metabase.jar
          RUN chown -R metabase:metabase /opt/metabase

          # set time zone
          RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
          ENTRYPOINT ["java", "-jar", "metabase.jar"]
        type: Dockerfile
      strategy:
        dockerStrategy:
          pullSecret:
            name: af2668-artifactory
          from:
            kind: DockerImage
            name: artifacts.developer.gov.bc.ca/redhat-docker-remote/ubi8:latest
        type: Docker
      triggers:
        - type: ConfigChange
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    required: true
    value: metabase
  - name: VERSION
    displayName: Image version tag
    description: The version tag of the built image
    required: true
    value: latest
