version: "3.5"

services:
  ## Build liquibase docker image
  lquibase:
    image: liquibase/liquibase:latest
    container_name: liquibase-container
    environment:
      - LIQUIBASE_COMMAND_USERNAME=${LIQUIBASE_COMMAND_USERNAME}
      - LIQUIBASE_COMMAND_PASSWORD=${LIQUIBASE_COMMAND_PASSWORD}
      - LIQUIBASE_COMMAND_URL=${LIQUIBASE_COMMAND_URL}
      - LIQUIBASE_PRO_LICENSE_KEY=${LIQUIBASE_PRO_LICENSE_KEY}
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=${LIQUIBASE_COMMAND_CHANGELOG_FILE}
    networks:
      - local-network
    volumes:
      - liquibase:/liquibase/changelog
    command: ["update-sql"]
networks:
  local-network:
    driver: bridge

volumes:
  liquibase:
    name: liquibase-vol
